Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: spring-boot-
    SupplierDeployMetadata:
      AcrImageArtifactRelation:
        '{{ computenest::acrimage::springBootDemo }}':
          ArtifactId: artifact-58a1ffbe260e490dbc52
    TemplateConfigs:
      - Name: 容器集群部署yaml模版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'docs/architecture.png'
        AllowedRegions:
          - cn-qingdao
          - cn-beijing
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-hangzhou
          - cn-shanghai
          - cn-nanjing
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-fuzhou
          - cn-wuhan-lr
          - cn-chengdu
          - cn-hongkong
          - ap-northeast-1
          - ap-northeast-2
          - ap-southeast-1
          - ap-southeast-3
          - ap-southeast-6
          - ap-southeast-5
          - ap-southeast-7
          - us-east-1
          - us-west-1
          - na-south-1
          - eu-west-1
          - me-east-1
          - me-central-1
          - eu-central-1
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: spring boot demo，在容器集群上以yaml的方式部署spring boot应用
    Image: 'resources/icons/service_logo.png'
    Name: SpringBoot服务示例(容器集群+yaml版本)
  ShareType: Public
  ApprovalType: Manual
AcrImageBuilder:
  AcrImage_1:
    DockerFilePath: '.computenest/resources/artifact_resources/acr_image/Dockerfile'
    RepoName: spring-boot-demo
    Tag: v1.0

