Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: spring-boot-
    SupplierDeployMetadata:
      AcrImageArtifactRelation:
        '{{ computenest::acrimage::springBootDemo }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 容器集群部署yaml模版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'docs/architecture.png'
        AllowedRegions:
          - cn-hangzhou
          - cn-shanghai
          - cn-qingdao
          - cn-beijing
          - cn-huhehaote
          - cn-wulanchabu
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-chengdu
          - cn-hongkong
          - ap-southeast-1
          - ap-northeast-2
          - ap-southeast-3
          - ap-southeast-5
          - ap-northeast-1
          - eu-central-1
          - eu-west-1
          - us-west-1
          - us-east-1
          - ap-southeast-6
          - ap-southeast-7
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: spring boot demo，在容器集群上以yaml的方式部署spring boot应用
    Image: 'resources/icons/service_logo.png'
    Name: SpringBoot服务示例(容器集群+yaml版本)
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: AcrImage
    ArtifactName: spring-boot-demo
    Description: spring-boot-demo
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_1.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_1.Tag}
      RepoType: Public
AcrImageBuilder:
  AcrImage_1:
    DockerFilePath: '.computenest/resources/artifact_resources/acr_image/Dockerfile'
    RepoName: spring-boot-demo
    Tag: v1.0

